/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

/**
 *
 * @author Sergii.Tushinskyi
 */
public class OptionCSVDialog extends javax.swing.JDialog {

    private boolean ok;// флаг подтверждения операции
    private String separator = ";";// символ - разделитель по умолчанию ";"
    private boolean header;
    /**
     * Creates new form OptionCSVDialog
     * @param parent
     * @param modal
     */
    public OptionCSVDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        chkHeader = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        CommaRadioBtn = new javax.swing.JRadioButton();
        CommaPointRadioBtn = new javax.swing.JRadioButton();
        TwinPointRadioBtn = new javax.swing.JRadioButton();
        YesButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        chkHeader.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkHeader.setText("В первой строке заголовки столбцов");
        chkHeader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkHeaderActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Разделитель полей"));

        buttonGroup1.add(CommaRadioBtn);
        CommaRadioBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CommaRadioBtn.setText("Запятая");
        CommaRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommaRadioBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(CommaPointRadioBtn);
        CommaPointRadioBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CommaPointRadioBtn.setSelected(true);
        CommaPointRadioBtn.setText("Точка с запятой");
        CommaPointRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommaPointRadioBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(TwinPointRadioBtn);
        TwinPointRadioBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TwinPointRadioBtn.setText("Двоеточие");
        TwinPointRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwinPointRadioBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CommaRadioBtn)
                .addGap(39, 39, 39)
                .addComponent(CommaPointRadioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TwinPointRadioBtn)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CommaRadioBtn)
                    .addComponent(CommaPointRadioBtn)
                    .addComponent(TwinPointRadioBtn))
                .addGap(26, 26, 26))
        );

        YesButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        YesButton.setText("ОК");
        YesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesButtonActionPerformed(evt);
            }
        });

        CancelButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CancelButton.setText("Отмена");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(YesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(CancelButton)
                .addGap(115, 115, 115))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton)
                    .addComponent(YesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void YesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesButtonActionPerformed
        // скрываем диалоговое окно дополнительных настроек
        ok = true;// подтверждение выбора
        setVisible(false);
    }//GEN-LAST:event_YesButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        // скрываем диалоговое окно дополнительных настроек
        ok = false;// отмена выбора
        setVisible(false);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void CommaRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommaRadioBtnActionPerformed
        // TODO add your handling code here:
        separator = ",";
    }//GEN-LAST:event_CommaRadioBtnActionPerformed

    private void CommaPointRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommaPointRadioBtnActionPerformed
        // TODO add your handling code here:
        separator = ";";
    }//GEN-LAST:event_CommaPointRadioBtnActionPerformed

    private void TwinPointRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwinPointRadioBtnActionPerformed
        // TODO add your handling code here:
        separator = ":";
    }//GEN-LAST:event_TwinPointRadioBtnActionPerformed

    private void chkHeaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHeaderActionPerformed
        // TODO add your handling code here:
        header = chkHeader.isSelected();
        System.out.println("header=" + header);
    }//GEN-LAST:event_chkHeaderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionCSVDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionCSVDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionCSVDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionCSVDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            OptionCSVDialog dialog = new OptionCSVDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    dialog.setVisible(false);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JRadioButton CommaPointRadioBtn;
    private javax.swing.JRadioButton CommaRadioBtn;
    private javax.swing.JRadioButton TwinPointRadioBtn;
    private javax.swing.JButton YesButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkHeader;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the ok
     */
    public boolean isOk() {
        return ok;
    }

    /**
     * @return the separator
     */
    public String getSeparator() {
        return separator;
    }

    /**
     * @return the header
     */
    public boolean isHeader() {
        return header;
    }

    /**
     * @param header the header to set
     */
    public void setHeader(boolean header) {
        this.header = header;
    }
}
